name: CI/CD Deploy bonkgames.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies & Build
      run: |
        npm ci
        npm run build

    - name: Prepare SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Add server to known_hosts
      run: |
        mkdir -p ~/.ssh
        # toma todo DEPLOY_SERVER
        server="${{ secrets.DEPLOY_SERVER }}"
        # extrae lo que venga después de la "@"
        host="${server#*@}"
        echo "Adding $host to known_hosts"
        ssh-keyscan -H "$host" >> ~/.ssh/known_hosts
      
    - name: Sync dist to server
      run: |
        rsync -avz --delete \
          ./dist/ \
          ${{ secrets.DEPLOY_SERVER }}:/var/www/html/bonkgames-app/dist/


    - name: Reload Nginx
      run: |
        ssh ${{ secrets.DEPLOY_SERVER }} "sudo systemctl reload nginx"
